---

circleCi:
  integrationToken: ${CIRCLECI_INTEGRATION_TOKEN} #set this to your token value
server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8081}
gitlab:
  authToken: ${GITLAB_AUTH_TOKEN} #set this to gitlab's user token value