---

circleCi:
  apiToken: ${CIRCLECI_API_TOKEN:-set this to your token value}
server:
  applicationConnectors:
    - type: http
      port: ${PORT:-8080}
  adminConnectors:
    - type: http
      port: ${ADMIN_PORT:-8081}
