package com.circleci.connector.gitlab.singleorg.model;

import java.util.UUID;
import javax.annotation.Nullable;
import org.immutables.value.Value;
import org.immutables.value.Value.Derived;

@Value.Immutable
@Value.Style(allParameters = true)
public abstract class Pipeline {
  public enum State {
    PENDING,
    RUNNING,
    SUCCESS,
    FAILED,
    CANCELED
  }

  /** @return the pipeline id generated by CircleCI, null if pipeline wasn't triggered yet */
  @Nullable
  public abstract UUID id();

  /** @return the project id as provided by GitLab */
  public abstract int projectId();

  public abstract State state();

  public abstract String revision();

  public abstract String branch();

  @Derived
  public boolean triggered() {
    return (this.id() != null);
  }
}
