package com.circleci.connector.gitlab.singleorg.model;

import java.util.Set;
import java.util.UUID;
import javax.annotation.Nullable;
import org.immutables.value.Value;
import org.immutables.value.Value.Derived;

@Value.Immutable
public abstract class Pipeline {
  /** @return the pipeline id generated by CircleCI, null if pipeline wasn't triggered yet */
  @Nullable
  @Value.Parameter
  public abstract UUID id();

  /** @return the project id as provided by GitLab */
  @Value.Parameter
  public abstract int projectId();

  @Value.Parameter
  public abstract String revision();

  @Value.Parameter
  public abstract String branch();

  @Derived
  public boolean triggered() {
    return (this.id() != null);
  }

  public abstract Set<Workflow> workflows();
}
